# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rluria_list <- function(n = 10L, rate = 1e-8, N0 = 1, Nt = 1e9, mut_fit = 1.0, death_prob = 0, lag = 0, e = 1, cv = 0, trim = 0L) {
    .Call(`_mlemur_rluria_list`, n, rate, N0, Nt, mut_fit, death_prob, lag, e, cv, trim)
}

rluria_vec <- function(n = 10L, rate = 1e-8, N0 = 1, Nt = 1e9, mut_fit = 1.0, death_prob = 0, lag = 0, e = 1, cv = 0, trim = 0L) {
    .Call(`_mlemur_rluria_vec`, n, rate, N0, Nt, mut_fit, death_prob, lag, e, cv, trim)
}

aux_seq_integrate_s <- function(e = 1, w = 1, d = 0, lag = 0, phi = 0, n = 10L) {
    .Call(`_mlemur_aux_seq_integrate_s`, e, w, d, lag, phi, n)
}

aux_seq <- function(e, w, n, option = 0L) {
    .Call(`_mlemur_aux_seq`, e, w, n, option)
}

aux_seq_lag_s <- function(e = 1, lag = 0, n = 10L) {
    .Call(`_mlemur_aux_seq_lag_s`, e, lag, n)
}

aux_seq_lag_s_ext <- function(e, lag, n, boost = FALSE) {
    .Call(`_mlemur_aux_seq_lag_s_ext`, e, lag, n, boost)
}

aux_seq_death_ext <- function(e, w, d, n, boost = FALSE) {
    .Call(`_mlemur_aux_seq_death_ext`, e, w, d, n, boost)
}

prob_ld <- function(m, seq, len) {
    .Call(`_mlemur_prob_ld`, m, seq, len)
}

xi_seq <- function(A, seq, len) {
    .Call(`_mlemur_xi_seq`, A, seq, len)
}

prob_b0 <- function(A, k, seq0, xi, len) {
    .Call(`_mlemur_prob_b0`, A, k, seq0, xi, len)
}

calc_probs <- function(m, cv, seq, len, poisson = 0, boost = FALSE) {
    .Call(`_mlemur_calc_probs`, m, cv, seq, len, poisson, boost)
}

logprob <- function(m, len, data, seq, k = 0, poisson = 0) {
    .Call(`_mlemur_logprob`, m, len, data, seq, k, poisson)
}

logprob_boost <- function(xm, len, data, seq, xk = 0, xpoisson = 0) {
    .Call(`_mlemur_logprob_boost`, xm, len, data, seq, xk, xpoisson)
}

optim_m <- function(current_m, lower_m, upper_m, seq, len, data, k, poisson, verbose = FALSE) {
    .Call(`_mlemur_optim_m`, current_m, lower_m, upper_m, seq, len, data, k, poisson, verbose)
}

root_m <- function(current_m, lower_m, upper_m, seq, len, data, k, poisson, lalpha, verbose = FALSE) {
    .Call(`_mlemur_root_m`, current_m, lower_m, upper_m, seq, len, data, k, poisson, lalpha, verbose)
}

combo_optim_m <- function(current_m, lower_m, upper_m, R, seq1, seq2, len1, len2, data1, data2, k1, k2, poisson1, poisson2, verbose = FALSE) {
    .Call(`_mlemur_combo_optim_m`, current_m, lower_m, upper_m, R, seq1, seq2, len1, len2, data1, data2, k1, k2, poisson1, poisson2, verbose)
}

optim_m_every_Nt <- function(current_m, lower_m, upper_m, R, seqs, data, k, poisson, verbose = FALSE) {
    .Call(`_mlemur_optim_m_every_Nt`, current_m, lower_m, upper_m, R, seqs, data, k, poisson, verbose)
}

root_m_every_Nt <- function(current_m, lower_m, upper_m, seqs, R, data, k, poisson, lalpha, verbose = FALSE) {
    .Call(`_mlemur_root_m_every_Nt`, current_m, lower_m, upper_m, seqs, R, data, k, poisson, lalpha, verbose)
}

aux_seq_integrate_s_n0 <- function(e = 1, w = 1, d = 0, lag = 0, phi = 0, n = 10L, n0 = 0L) {
    .Call(`_mlemur_aux_seq_integrate_s_n0`, e, w, d, lag, phi, n, n0)
}

aux_seq_ext_n0 <- function(e = 1, w = 0, n = 10L, boost = FALSE, n0 = 0L) {
    .Call(`_mlemur_aux_seq_ext_n0`, e, w, n, boost, n0)
}

aux_seq_lag_s_ext_n0 <- function(e = 1, lag = 0, n = 10L, boost = FALSE, n0 = 0L) {
    .Call(`_mlemur_aux_seq_lag_s_ext_n0`, e, lag, n, boost, n0)
}

aux_seq_death_ext_n0 <- function(e, w, d, n, boost = FALSE, n0 = 0L) {
    .Call(`_mlemur_aux_seq_death_ext_n0`, e, w, d, n, boost, n0)
}

prob_mutations_n0_boost <- function(m, e = 1, w = 1, cv = 0, death = 0, lag = 0, phi = 0, poisson = 0, cdf = 0.99, maxiter = 10L) {
    .Call(`_mlemur_prob_mutations_n0_boost`, m, e, w, cv, death, lag, phi, poisson, cdf, maxiter)
}

prob_mutations_n0 <- function(m, e = 1, w = 1, cv = 0, death = 0, lag = 0, phi = 0, poisson = 0, cdf = 0.99, maxiter = 10L) {
    .Call(`_mlemur_prob_mutations_n0`, m, e, w, cv, death, lag, phi, poisson, cdf, maxiter)
}

optim_m_from_probs <- function(current_m, lower_m, upper_m, R, k1, k2, poisson1, poisson2, seq1, seq2, prob1, prob2, m1, m2, prob1_boost, prob2_boost, verbose = FALSE) {
    .Call(`_mlemur_optim_m_from_probs`, current_m, lower_m, upper_m, R, k1, k2, poisson1, poisson2, seq1, seq2, prob1, prob2, m1, m2, prob1_boost, prob2_boost, verbose)
}

